name: proximity_screen_lock_ios_example
description: "Demonstrates how to use the proximity_screen_lock_ios plugin."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.19.0"

dependencies:
  flutter:
    sdk: flutter

  proximity_screen_lock_ios:
    path: ../

  cupertino_icons: ^1.0.8

dependency_overrides:
  proximity_screen_lock_platform_interface:
    path: ../../proximity_screen_lock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
