name: proximity_screen_lock_default
description: A default plugin that can be used to bind screen activation to proximity sensor
version: 1.0.0
homepage: https://github.com/amantoux/proximity_screen_lock
repository: https://github.com/amantoux/proximity_screen_lock/tree/master/proximity_screen_lock

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  proximity_screen_lock_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
