name: proximity_screen_lock_default
description: A plugin that can be used to bind screen activation to proximity sensor
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  proximity_screen_lock_platform_interface:
    path: ../proximity_screen_lock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ProximityScreenLockDefault
        fileName: proximity_screen_lock_default.dart
