name: proximity_screen_lock_platform_interface
description: A platform interface plugin for proximity screen lock plugins
version: 2.1.1
homepage: https://github.com/amantoux/proximity_screen_lock
repository: https://github.com/amantoux/proximity_screen_lock/tree/master/proximity_screen_lock_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
