name: proximity_screen_lock_platform_interface
description: A platform interface plugin for proximity screen lock plugins
version: 1.0.1
homepage: https://github.com/amantoux/proximity_screen_lock
repository: https://github.com/amantoux/proximity_screen_lock/tree/master/proximity_screen_lock_platform_interface

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
