name: proximity_screen_lock_ios
description: A iOS Flutter plugin that can be used to bind screen activation to proximity sensor
version: 2.1.1
homepage: https://github.com/amantoux/proximity_screen_lock
repository: https://github.com/amantoux/proximity_screen_lock/tree/master/proximity_screen_lock_ios

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.19.0"

dependencies:
  flutter:
    sdk: flutter
  proximity_screen_lock_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: proximity_screen_lock
    platforms:
      ios:
        pluginClass: ProximityScreenLockIosPlugin
        dartPluginClass: ProximityScreenLockIos
